apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwamx-web-development
  labels:
    app: qwamx-web-development
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwamx-web-development
  template:
    metadata:
      labels:
        app: qwamx-web-development
    spec:
      containers:
      - name: qwamx-web
        image: asobeeh/pythonapp:22
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 3000
        # resources:
          # limits:
          #   memory: 1024Mi
          #   cpu: "1"
          # requests:
          #   memory: 256Mi
          #   cpu: "0.2"
        ports: 
        - containerPort: 3000
        env:
      imagePullSecrets:
      - name: simpleapp
